/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef MATHSUITE_PRIVATE_H
#define MATHSUITE_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.4.0.650"
#define VER_MAJOR	1
#define VER_MINOR	4
#define VER_RELEASE	0
#define VER_BUILD	650
#define COMPANY_NAME	"NextGenLab - OBSIDIAN Environmenting"
#define FILE_VERSION	"1.4.0.650"
#define FILE_DESCRIPTION	"msp"
#define INTERNAL_NAME	"mSp"
#define LEGAL_COPYRIGHT	"Protected by CC BY-SA 2.0"
#define LEGAL_TRADEMARKS	"Protected by CC BY-SA 2.0"
#define ORIGINAL_FILENAME	"msp v1.40"
#define PRODUCT_NAME	"msp"
#define PRODUCT_VERSION	"1.4.0.650"

#endif /*MATHSUITE_PRIVATE_H*/
